version: "3"

services:
  aws-sam-local:
    container_name: lambda-api
    build:
        context: ./api
        dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./api:/api
  dynamodb-local:
    container_name: dynamodb
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
    command: -jar DynamoDBLocal.jar -dbPath /data -sharedDb
    volumes:
      - ./data:/data
    networks:
      - lambda-local
  spa:
    container_name: vue-spa
    build: 
      context: ./spa
      dockerfile: Dockerfile
    ports:
        - 8080:8080
    volumes: 
        - ./spa:/app
      
networks:
  lambda-local:
    external: true