version: "3"

services:
  aws-sam-local:
    image: cnadiminti/aws-sam-local
    command: local start-api --docker-volume-basedir "$PWD/api" --host 0.0.0.0
    ports:
      - '3000:3000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./api:/var/opt
  dynamodb-local:
    container_name: dynamodb
    image: amazon/dynamodb-local
    build: ./
    ports:
      - 8000:8000
    command: -jar DynamoDBLocal.jar -dbPath /data -sharedDb
    volumes:
      - ./data:/data
    networks:
      - lambda-local
  spa:
    container_name: vue-spa
    build: 
      context: ./spa/
      dockerfile: Dockerfile
    ports:
        - 8080:8080
    volumes: 
        - .:/app
      
networks:
  lambda-local:
    external: true