name: build and test

on:
  push:
    branches:
      - master
      - staging
  pull_request:

jobs:
  api:
    name: test API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
    - uses: actions/checkout@v2

  spa:
    name: test SPA
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: spa
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: npm install
    - run: npm test