name: build and test

on:
  push:
    branches:
      - master
      - staging
  pull_request:

jobs:
  api:


  spa:
    name: build and deploy to s3
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: npm install
    - run: npm test