name: Deploy to production
on:
  workflow_run:
    workflows:
      - build-test
    branches:
      - main
    types:
      - completed
jobs:
  api:
    name: deploy SAM
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
    - uses: actions/checkout@v2
    - uses: falnyr/aws-sam-deploy-action@v1.2.1
    # https://github.com/marketplace/actions/aws-sam-deploy
      env:
        TEMPLATE: 'template.yaml'
        AWS_STACK_NAME: demo-api
        AWS_REGION: 'us-east-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEPLOY_BUCKET: ${{ secrets.AWS_DEPLOY_BUCKET }}

  spa:
    name: build and deploy to s3
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: spa
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: npm install
    - run: npm test
    - run: npm build
    - uses: reggionick/s3-deploy@v3
    # https://github.com/marketplace/actions/s3-deploy
      with:
        folder: build
        bucket: ${{ secrets.S3_BUCKET }}
        bucket-region: ${{ secrets.S3_BUCKET_REGION }}
        dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        invalidation: /
        delete-removed: true
        no-cache: true
        private: true